#!/bin/bash

python3 yaml2nxdl.py --verbose --input-file NXaberration.yaml
python3 yaml2nxdl.py --verbose --input-file NXaperture_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXapm.yaml
python3 yaml2nxdl.py --verbose --input-file NXchamber.yaml
python3 yaml2nxdl.py --verbose --input-file NXcoordinate_system_set.yaml
python3 yaml2nxdl.py --verbose --input-file NXcorrector_cs.yaml
python3 yaml2nxdl.py --verbose --input-file NXebeam_column.yaml
python3 yaml2nxdl.py --verbose --input-file NXem.yaml
python3 yaml2nxdl.py --verbose --input-file NXevent_data_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXevent_data_em_set.yaml
python3 yaml2nxdl.py --verbose --input-file NXibeam_column.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_adf.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_bf.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_bse.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_chamber.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_df.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_diffrac.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_ecci.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_kikuchi.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_ronchigram.yaml
python3 yaml2nxdl.py --verbose --input-file NXimage_set_em_se.yaml
python3 yaml2nxdl.py --verbose --input-file NXinteraction_vol_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXion.yaml
python3 yaml2nxdl.py --verbose --input-file NXlens_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXmanufacturer.yaml
python3 yaml2nxdl.py --verbose --input-file NXoptical_system_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXpeak.yaml
python3 yaml2nxdl.py --verbose --input-file NXpulser_apm.yaml
python3 yaml2nxdl.py --verbose --input-file NXpump.yaml
python3 yaml2nxdl.py --verbose --input-file NXreflectron.yaml
python3 yaml2nxdl.py --verbose --input-file NXscanbox_em.yaml
python3 yaml2nxdl.py --verbose --input-file NXspectrum_set_em_auger.yaml
python3 yaml2nxdl.py --verbose --input-file NXspectrum_set_em_cathodolum.yaml
python3 yaml2nxdl.py --verbose --input-file NXspectrum_set_em_eels.yaml
python3 yaml2nxdl.py --verbose --input-file NXspectrum_set_em_xray.yaml
python3 yaml2nxdl.py --verbose --input-file NXstage_lab.yaml
